--------------------------------------------------------------------------------
-- V1: Tablas base de usuarios y roles
--------------------------------------------------------------------------------

-- Tabla de roles
CREATE TABLE roles
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR2(64)   NOT NULL,
    name        VARCHAR2(128)  NOT NULL,
    description VARCHAR2(512),
    is_system   NUMBER(1)      DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    created_by  VARCHAR2(128),
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_by  VARCHAR2(128),
    CONSTRAINT uk_roles_code UNIQUE (code)
);

-- Tabla de usuarios
CREATE TABLE users
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(60)   NOT NULL,
    last_name     VARCHAR2(60)   NOT NULL,
    email         VARCHAR2(320)  NOT NULL,
    email_norm    VARCHAR2(320)  GENERATED ALWAYS AS (LOWER(TRIM(email))) VIRTUAL,
    password_hash VARCHAR2(255)  NOT NULL,
    enabled       NUMBER(1)      DEFAULT 1 NOT NULL,
    locked        NUMBER(1)      DEFAULT 0 NOT NULL,
    mfa_enabled   NUMBER(1)      DEFAULT 0 NOT NULL,
    last_login_at TIMESTAMP(6) WITH TIME ZONE,
    created_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    created_by    VARCHAR2(128),
    updated_at    TIMESTAMP(6) WITH TIME ZONE,
    updated_by    VARCHAR2(128),
    deleted_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_users_email_norm UNIQUE (email_norm)
);

-- Relación muchos-a-muchos usuario <-> roles
CREATE TABLE user_roles
(
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE INDEX ix_user_roles_user ON user_roles (user_id);
CREATE INDEX ix_user_roles_role ON user_roles (role_id);
