CREATE TABLE request_logs
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER,
    email       VARCHAR2(320),
    method      VARCHAR2(10)   NOT NULL,
    path        VARCHAR2(512)  NOT NULL,
    status_code NUMBER                                           NOT NULL,
    success     NUMBER(1)      DEFAULT 1 NOT NULL,
    ip_address  VARCHAR2(45),
    user_agent  VARCHAR2(512),
    occurred_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX ix_request_logs_user ON request_logs (user_id);
CREATE INDEX ix_request_logs_path ON request_logs (path);
CREATE INDEX ix_request_logs_time ON request_logs (occurred_at);
CREATE INDEX ix_request_logs_status ON request_logs (status_code);
